language: node_js
node_js:
  - "node"
script: yarn lint

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn cover && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage